/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author migue
 */
public class PanelMonitor extends javax.swing.JPanel {

    /**
     * Creates new form PanelMonitor
     */
    public PanelMonitor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneMonitores = new javax.swing.JScrollPane();
        TableMonitores = new javax.swing.JTable();
        LabelGestionMonitores = new javax.swing.JLabel();
        ButtonNuevoMonitor = new javax.swing.JButton();
        ButtonBajaMonitor = new javax.swing.JButton();
        ButtonActualizacionMonitor = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 51));

        TableMonitores.setBackground(new java.awt.Color(204, 204, 204));
        TableMonitores.setForeground(new java.awt.Color(0, 0, 0));
        TableMonitores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneMonitores.setViewportView(TableMonitores);

        LabelGestionMonitores.setBackground(new java.awt.Color(255, 255, 255));
        LabelGestionMonitores.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelGestionMonitores.setText("GESTIÓN DE MONITORES");
        LabelGestionMonitores.setToolTipText("");

        ButtonNuevoMonitor.setBackground(new java.awt.Color(0, 153, 51));
        ButtonNuevoMonitor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonNuevoMonitor.setText("Nuevo Monitor");
        ButtonNuevoMonitor.setActionCommand("nuevoMonitor");
        ButtonNuevoMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNuevoMonitorActionPerformed(evt);
            }
        });

        ButtonBajaMonitor.setBackground(new java.awt.Color(204, 51, 0));
        ButtonBajaMonitor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonBajaMonitor.setText("Baja de Monitor");
        ButtonBajaMonitor.setActionCommand("bajaMonitor");
        ButtonBajaMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBajaMonitorActionPerformed(evt);
            }
        });

        ButtonActualizacionMonitor.setBackground(new java.awt.Color(204, 204, 204));
        ButtonActualizacionMonitor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonActualizacionMonitor.setForeground(new java.awt.Color(0, 0, 0));
        ButtonActualizacionMonitor.setText("Actualización de Monitor");
        ButtonActualizacionMonitor.setActionCommand("actualizaMonitor");
        ButtonActualizacionMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActualizacionMonitorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneMonitores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(LabelGestionMonitores))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ButtonNuevoMonitor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonBajaMonitor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonActualizacionMonitor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(LabelGestionMonitores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneMonitores, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonNuevoMonitor)
                    .addComponent(ButtonBajaMonitor)
                    .addComponent(ButtonActualizacionMonitor))
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonNuevoMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNuevoMonitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonNuevoMonitorActionPerformed

    private void ButtonBajaMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBajaMonitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonBajaMonitorActionPerformed

    private void ButtonActualizacionMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActualizacionMonitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonActualizacionMonitorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ButtonActualizacionMonitor;
    public javax.swing.JButton ButtonBajaMonitor;
    public javax.swing.JButton ButtonNuevoMonitor;
    public javax.swing.JLabel LabelGestionMonitores;
    public javax.swing.JTable TableMonitores;
    public javax.swing.JScrollPane jScrollPaneMonitores;
    // End of variables declaration//GEN-END:variables
}
