/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

/**
 *
 * @author migue
 */
public class VistaConsultaActividad extends javax.swing.JDialog {

    /**
     * Creates new form VistaNuevoSocio
     */
    public VistaConsultaActividad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGestionInscripciones = new javax.swing.JPanel();
        ButtonVerCuota = new javax.swing.JButton();
        LabelConsultaActividad = new javax.swing.JLabel();
        LabelCodigoActividad = new javax.swing.JLabel();
        TextFieldCodActividad = new javax.swing.JTextField();
        LabelMonitor = new javax.swing.JLabel();
        LabelNumSocios = new javax.swing.JLabel();
        LabelPrecioBase = new javax.swing.JLabel();
        LabelCuotaMensual = new javax.swing.JLabel();
        LabelCuotaMensualDescuentos = new javax.swing.JLabel();
        LabelMonitor1 = new javax.swing.JLabel();
        LabelNumSocios1 = new javax.swing.JLabel();
        LabelPrecioBase1 = new javax.swing.JLabel();
        LabelCuotaMensual1 = new javax.swing.JLabel();
        LabelCuotaMensualDescuentos1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PanelGestionInscripciones.setBackground(new java.awt.Color(0, 0, 51));

        ButtonVerCuota.setBackground(new java.awt.Color(204, 204, 204));
        ButtonVerCuota.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonVerCuota.setForeground(new java.awt.Color(0, 0, 0));
        ButtonVerCuota.setText("Ver Cuota");
        ButtonVerCuota.setActionCommand("verCuota");
        ButtonVerCuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVerCuotaActionPerformed(evt);
            }
        });

        LabelConsultaActividad.setBackground(new java.awt.Color(255, 255, 255));
        LabelConsultaActividad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelConsultaActividad.setText("CONSULTA ACTIVIDAD");
        LabelConsultaActividad.setToolTipText("");

        LabelCodigoActividad.setText("Código de la Actividad");

        TextFieldCodActividad.setBackground(new java.awt.Color(255, 255, 255));
        TextFieldCodActividad.setForeground(new java.awt.Color(0, 0, 0));
        TextFieldCodActividad.setActionCommand("<Not Set>");
        TextFieldCodActividad.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        LabelMonitor.setText("Monitor:");

        LabelNumSocios.setText("Número de Socios:");

        LabelPrecioBase.setText("Precio Base:");

        LabelCuotaMensual.setText("Cuota Mensual:");

        LabelCuotaMensualDescuentos.setText("Cuota Mensual (con descuentos):");

        LabelMonitor1.setText("Monitor");

        LabelNumSocios1.setText("Número de Socios");

        LabelPrecioBase1.setText("Precio Base");

        LabelCuotaMensual1.setText("Cuota Mensual");

        LabelCuotaMensualDescuentos1.setText("Cuota Mensual (d)");

        javax.swing.GroupLayout PanelGestionInscripcionesLayout = new javax.swing.GroupLayout(PanelGestionInscripciones);
        PanelGestionInscripciones.setLayout(PanelGestionInscripcionesLayout);
        PanelGestionInscripcionesLayout.setHorizontalGroup(
            PanelGestionInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGestionInscripcionesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(PanelGestionInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGestionInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(LabelConsultaActividad)
                        .addGroup(PanelGestionInscripcionesLayout.createSequentialGroup()
                            .addComponent(LabelCodigoActividad)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(TextFieldCodActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)))
                    .addComponent(LabelMonitor)
                    .addComponent(LabelNumSocios)
                    .addComponent(LabelPrecioBase)
                    .addComponent(LabelCuotaMensual)
                    .addComponent(LabelCuotaMensualDescuentos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelGestionInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelCuotaMensualDescuentos1)
                    .addComponent(LabelCuotaMensual1)
                    .addComponent(LabelPrecioBase1)
                    .addComponent(LabelNumSocios1)
                    .addComponent(LabelMonitor1)
                    .addComponent(ButtonVerCuota))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        PanelGestionInscripcionesLayout.setVerticalGroup(
            PanelGestionInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGestionInscripcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelConsultaActividad)
                .addGap(40, 40, 40)
                .addGroup(PanelGestionInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCodigoActividad)
                    .addComponent(TextFieldCodActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonVerCuota))
                .addGap(56, 56, 56)
                .addGroup(PanelGestionInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelMonitor)
                    .addComponent(LabelMonitor1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelGestionInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNumSocios)
                    .addComponent(LabelNumSocios1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelGestionInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPrecioBase)
                    .addComponent(LabelPrecioBase1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelGestionInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCuotaMensual)
                    .addComponent(LabelCuotaMensual1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelGestionInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCuotaMensualDescuentos)
                    .addComponent(LabelCuotaMensualDescuentos1))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelGestionInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGestionInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonVerCuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVerCuotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonVerCuotaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ButtonVerCuota;
    public javax.swing.JLabel LabelCodigoActividad;
    public javax.swing.JLabel LabelConsultaActividad;
    public javax.swing.JLabel LabelCuotaMensual;
    public javax.swing.JLabel LabelCuotaMensual1;
    public javax.swing.JLabel LabelCuotaMensualDescuentos;
    public javax.swing.JLabel LabelCuotaMensualDescuentos1;
    public javax.swing.JLabel LabelMonitor;
    public javax.swing.JLabel LabelMonitor1;
    public javax.swing.JLabel LabelNumSocios;
    public javax.swing.JLabel LabelNumSocios1;
    public javax.swing.JLabel LabelPrecioBase;
    public javax.swing.JLabel LabelPrecioBase1;
    public javax.swing.JPanel PanelGestionInscripciones;
    public javax.swing.JTextField TextFieldCodActividad;
    // End of variables declaration//GEN-END:variables
}
