
package Vista;

public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuBarPrincipal = new javax.swing.JMenuBar();
        MenuHome = new javax.swing.JMenu();
        MenuItemHome = new javax.swing.JMenuItem();
        MenuMonitores = new javax.swing.JMenu();
        MenuItemGestionMonitores = new javax.swing.JMenuItem();
        MenuItemCuotaMonitor = new javax.swing.JMenuItem();
        MenuSocios = new javax.swing.JMenu();
        MenuItemGestionSocios = new javax.swing.JMenuItem();
        MenuActividades = new javax.swing.JMenu();
        MenuAmpliacion = new javax.swing.JMenu();
        menuItemActualizacionCategorias = new javax.swing.JMenuItem();
        menuItemCuotaActividad = new javax.swing.JMenuItem();
        MenuSalir = new javax.swing.JMenu();
        MenuItemSalirAplicacion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imgHome2.png"))); // NOI18N
        MenuHome.setActionCommand("desplegarHome");

        MenuItemHome.setText("Home");
        MenuItemHome.setActionCommand("salirHome");
        MenuHome.add(MenuItemHome);

        MenuBarPrincipal.add(MenuHome);

        MenuMonitores.setText("Monitores");
        MenuMonitores.setActionCommand("desplegarMenuMonitores");

        MenuItemGestionMonitores.setText("Gestión de Monitores");
        MenuItemGestionMonitores.setActionCommand("gestionMonitores");
        MenuItemGestionMonitores.setMargin(null);
        MenuMonitores.add(MenuItemGestionMonitores);

        MenuItemCuotaMonitor.setText("Cuota de Monitor");
        MenuItemCuotaMonitor.setActionCommand("cuotaMonitor");
        MenuMonitores.add(MenuItemCuotaMonitor);

        MenuBarPrincipal.add(MenuMonitores);

        MenuSocios.setText("Socios");
        MenuSocios.setActionCommand("desplegarMenuSocios");

        MenuItemGestionSocios.setText("Gestión de Socios");
        MenuItemGestionSocios.setActionCommand("gestionSocios");
        MenuSocios.add(MenuItemGestionSocios);

        MenuBarPrincipal.add(MenuSocios);

        MenuActividades.setText("Actividades");
        MenuActividades.setActionCommand("desplegarMenuActividades");
        MenuBarPrincipal.add(MenuActividades);

        MenuAmpliacion.setText("Ampliación");
        MenuAmpliacion.setActionCommand("menuAmpliacion");

        menuItemActualizacionCategorias.setText("Actualización de Categorías");
        menuItemActualizacionCategorias.setActionCommand("actualizacionCategorias");
        MenuAmpliacion.add(menuItemActualizacionCategorias);

        menuItemCuotaActividad.setText("Cuota de Actividad");
        menuItemCuotaActividad.setActionCommand("cuotaActividad");
        menuItemCuotaActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCuotaActividadActionPerformed(evt);
            }
        });
        MenuAmpliacion.add(menuItemCuotaActividad);

        MenuBarPrincipal.add(MenuAmpliacion);

        MenuSalir.setText("Salir");
        MenuSalir.setActionCommand("SalirPrincipal");

        MenuItemSalirAplicacion.setText("Salir de la aplicación");
        MenuItemSalirAplicacion.setActionCommand("salirAplicacion");
        MenuSalir.add(MenuItemSalirAplicacion);

        MenuBarPrincipal.add(MenuSalir);

        setJMenuBar(MenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemCuotaActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCuotaActividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemCuotaActividadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu MenuActividades;
    public javax.swing.JMenu MenuAmpliacion;
    public javax.swing.JMenuBar MenuBarPrincipal;
    public javax.swing.JMenu MenuHome;
    public javax.swing.JMenuItem MenuItemCuotaMonitor;
    public javax.swing.JMenuItem MenuItemGestionMonitores;
    public javax.swing.JMenuItem MenuItemGestionSocios;
    public javax.swing.JMenuItem MenuItemHome;
    public javax.swing.JMenuItem MenuItemSalirAplicacion;
    public javax.swing.JMenu MenuMonitores;
    public javax.swing.JMenu MenuSalir;
    public javax.swing.JMenu MenuSocios;
    public javax.swing.JMenuItem menuItemActualizacionCategorias;
    public javax.swing.JMenuItem menuItemCuotaActividad;
    // End of variables declaration//GEN-END:variables
}
