/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

/**
 *
 * @author migue
 */
public class VistaGestionInscripciones extends javax.swing.JDialog {

    /**
     * Creates new form VistaNuevoSocio
     */
    public VistaGestionInscripciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGestionInscripciones = new javax.swing.JPanel();
        ButtonAltaActividad = new javax.swing.JButton();
        ButtonBajaActividad = new javax.swing.JButton();
        LabelSocio = new javax.swing.JLabel();
        LabelGestionInscripciones = new javax.swing.JLabel();
        LabelNumeroSocio = new javax.swing.JLabel();
        LabelActividades = new javax.swing.JLabel();
        ComboBoxSeleccionActividad = new javax.swing.JComboBox<>();
        ButtonConfirmarAltaBaja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PanelGestionInscripciones.setBackground(new java.awt.Color(0, 0, 51));

        ButtonAltaActividad.setBackground(new java.awt.Color(0, 153, 51));
        ButtonAltaActividad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonAltaActividad.setForeground(new java.awt.Color(255, 255, 255));
        ButtonAltaActividad.setText("Dar de alta");
        ButtonAltaActividad.setActionCommand("altaActividad");
        ButtonAltaActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAltaActividadActionPerformed(evt);
            }
        });

        ButtonBajaActividad.setBackground(new java.awt.Color(204, 51, 0));
        ButtonBajaActividad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonBajaActividad.setText("Dar de baja");
        ButtonBajaActividad.setActionCommand("bajaActividad");
        ButtonBajaActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBajaActividadActionPerformed(evt);
            }
        });

        LabelSocio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelSocio.setText("Socio:");

        LabelGestionInscripciones.setBackground(new java.awt.Color(255, 255, 255));
        LabelGestionInscripciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelGestionInscripciones.setText("  GESTIÓN DE INSCRIPCIONES");
        LabelGestionInscripciones.setToolTipText("");

        LabelNumeroSocio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelNumeroSocio.setForeground(new java.awt.Color(255, 255, 0));
        LabelNumeroSocio.setText("S???");

        LabelActividades.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelActividades.setText("Selecciona una actividad:");

        ComboBoxSeleccionActividad.setBackground(new java.awt.Color(51, 51, 51));
        ComboBoxSeleccionActividad.setForeground(new java.awt.Color(255, 255, 255));

        ButtonConfirmarAltaBaja.setBackground(new java.awt.Color(204, 204, 204));
        ButtonConfirmarAltaBaja.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonConfirmarAltaBaja.setForeground(new java.awt.Color(0, 0, 0));
        ButtonConfirmarAltaBaja.setText("Confirmar ????");
        ButtonConfirmarAltaBaja.setActionCommand("confirmarAltaBaja");
        ButtonConfirmarAltaBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConfirmarAltaBajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelGestionInscripcionesLayout = new javax.swing.GroupLayout(PanelGestionInscripciones);
        PanelGestionInscripciones.setLayout(PanelGestionInscripcionesLayout);
        PanelGestionInscripcionesLayout.setHorizontalGroup(
            PanelGestionInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGestionInscripcionesLayout.createSequentialGroup()
                .addGroup(PanelGestionInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGestionInscripcionesLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(PanelGestionInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelActividades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComboBoxSeleccionActividad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(PanelGestionInscripcionesLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(PanelGestionInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ButtonAltaActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelSocio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelGestionInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelNumeroSocio)
                            .addComponent(ButtonBajaActividad)))
                    .addGroup(PanelGestionInscripcionesLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(ButtonConfirmarAltaBaja)))
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGestionInscripcionesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LabelGestionInscripciones)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelGestionInscripcionesLayout.setVerticalGroup(
            PanelGestionInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGestionInscripcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelGestionInscripciones)
                .addGap(44, 44, 44)
                .addGroup(PanelGestionInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelSocio)
                    .addComponent(LabelNumeroSocio))
                .addGap(28, 28, 28)
                .addGroup(PanelGestionInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAltaActividad)
                    .addComponent(ButtonBajaActividad))
                .addGap(45, 45, 45)
                .addComponent(LabelActividades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ComboBoxSeleccionActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(ButtonConfirmarAltaBaja)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGestionInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGestionInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAltaActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAltaActividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonAltaActividadActionPerformed

    private void ButtonBajaActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBajaActividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonBajaActividadActionPerformed

    private void ButtonConfirmarAltaBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConfirmarAltaBajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonConfirmarAltaBajaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ButtonAltaActividad;
    public javax.swing.JButton ButtonBajaActividad;
    public javax.swing.JButton ButtonConfirmarAltaBaja;
    public javax.swing.JComboBox<String> ComboBoxSeleccionActividad;
    public javax.swing.JLabel LabelActividades;
    public javax.swing.JLabel LabelGestionInscripciones;
    public javax.swing.JLabel LabelNumeroSocio;
    private javax.swing.JLabel LabelSocio;
    public javax.swing.JPanel PanelGestionInscripciones;
    // End of variables declaration//GEN-END:variables
}
