/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author migue
 */
public class VistaLogin extends javax.swing.JFrame {

    /**
     * Creates new form VistaLogin
     */
    public VistaLogin() {
        initComponents();
        //setIconImage(getIconImage());
    }
    
    @Override
    public Image getIconImage() {
         Image img = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Images/imgIcono.png"));
         return img;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLogin = new javax.swing.JPanel();
        ButtonSalirLogin = new javax.swing.JButton();
        ComboBoxBD = new javax.swing.JComboBox<>();
        LabelServidor = new javax.swing.JLabel();
        ButtonConectar = new javax.swing.JButton();
        LabelImgLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acceso a la app");
        setIconImage(getIconImage());

        PanelLogin.setBackground(new java.awt.Color(0, 153, 153));
        PanelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonSalirLogin.setBackground(new java.awt.Color(204, 51, 0));
        ButtonSalirLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonSalirLogin.setText("Salir");
        ButtonSalirLogin.setActionCommand("salirLogin");
        ButtonSalirLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalirLoginActionPerformed(evt);
            }
        });
        PanelLogin.add(ButtonSalirLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 84, -1));

        ComboBoxBD.setBackground(new java.awt.Color(204, 204, 204));
        ComboBoxBD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ComboBoxBD.setForeground(new java.awt.Color(0, 0, 0));
        ComboBoxBD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oracle", "MariaDB" }));
        ComboBoxBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxBDActionPerformed(evt);
            }
        });
        PanelLogin.add(ComboBoxBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 100, -1));

        LabelServidor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelServidor.setText("Servidor:");
        LabelServidor.setToolTipText("");
        PanelLogin.add(LabelServidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        ButtonConectar.setBackground(new java.awt.Color(0, 153, 51));
        ButtonConectar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonConectar.setText("Conectar");
        ButtonConectar.setActionCommand("conectar");
        ButtonConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConectarActionPerformed(evt);
            }
        });
        PanelLogin.add(ButtonConectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));

        LabelImgLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IMG-20231126-WA0031.png"))); // NOI18N
        PanelLogin.add(LabelImgLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(PanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxBDActionPerformed

    private void ButtonConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConectarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonConectarActionPerformed

    private void ButtonSalirLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalirLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonSalirLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ButtonConectar;
    public javax.swing.JButton ButtonSalirLogin;
    public javax.swing.JComboBox<String> ComboBoxBD;
    public javax.swing.JLabel LabelImgLogin;
    public javax.swing.JLabel LabelServidor;
    public javax.swing.JPanel PanelLogin;
    // End of variables declaration//GEN-END:variables
}
