/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

/**
 *
 * @author migue
 */
public class VistaNuevoMonitor extends javax.swing.JDialog {

    /**
     * Creates new form VistaNuevoSocio
     */
    public VistaNuevoMonitor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelNuevoSocio = new javax.swing.JPanel();
        LabelCodigo = new javax.swing.JLabel();
        TextFieldCodigo = new javax.swing.JTextField();
        LabelNombre = new javax.swing.JLabel();
        TextFieldNombre = new javax.swing.JTextField();
        LabelDNI = new javax.swing.JLabel();
        TextFieldDNI = new javax.swing.JTextField();
        LabelTelefono = new javax.swing.JLabel();
        TextFieldTelefono = new javax.swing.JTextField();
        LabelCorreo = new javax.swing.JLabel();
        TextFieldCorreo = new javax.swing.JTextField();
        LabelFechaEntrada = new javax.swing.JLabel();
        LabelNick = new javax.swing.JLabel();
        TextFieldNick = new javax.swing.JTextField();
        ButtonInsertarMonitor = new javax.swing.JButton();
        ButtonCancelarInsertarMonitor = new javax.swing.JButton();
        DateChooserFechaEntrada = new com.toedter.calendar.JDateChooser();
        LabelAsteriscoDNI = new javax.swing.JLabel();
        LabelAsteriscoFEnt = new javax.swing.JLabel();
        LabelAsteriscoNombre = new javax.swing.JLabel();
        LabelAsteriscoTlf = new javax.swing.JLabel();
        LabelAsteriscoCorreo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PanelNuevoSocio.setBackground(new java.awt.Color(0, 0, 51));

        LabelCodigo.setText("Código");

        TextFieldCodigo.setEditable(false);
        TextFieldCodigo.setBackground(new java.awt.Color(195, 195, 195));
        TextFieldCodigo.setForeground(new java.awt.Color(0, 0, 0));
        TextFieldCodigo.setActionCommand("<Not Set>");
        TextFieldCodigo.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        LabelNombre.setText("Nombre");

        TextFieldNombre.setBackground(new java.awt.Color(255, 255, 255));
        TextFieldNombre.setForeground(new java.awt.Color(0, 0, 0));
        TextFieldNombre.setActionCommand("<Not Set>");
        TextFieldNombre.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        LabelDNI.setText("DNI");

        TextFieldDNI.setBackground(new java.awt.Color(255, 255, 255));
        TextFieldDNI.setForeground(new java.awt.Color(0, 0, 0));
        TextFieldDNI.setActionCommand("<Not Set>");
        TextFieldDNI.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        TextFieldDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldDNIActionPerformed(evt);
            }
        });

        LabelTelefono.setText("Teléfono");

        TextFieldTelefono.setBackground(new java.awt.Color(255, 255, 255));
        TextFieldTelefono.setForeground(new java.awt.Color(0, 0, 0));
        TextFieldTelefono.setActionCommand("<Not Set>");
        TextFieldTelefono.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        LabelCorreo.setText("Correo");

        TextFieldCorreo.setBackground(new java.awt.Color(255, 255, 255));
        TextFieldCorreo.setForeground(new java.awt.Color(0, 0, 0));
        TextFieldCorreo.setActionCommand("<Not Set>");
        TextFieldCorreo.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        LabelFechaEntrada.setText("Fecha de entrada");

        LabelNick.setText("Nick");

        TextFieldNick.setBackground(new java.awt.Color(255, 255, 255));
        TextFieldNick.setForeground(new java.awt.Color(0, 0, 0));
        TextFieldNick.setActionCommand("<Not Set>");
        TextFieldNick.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        TextFieldNick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNickActionPerformed(evt);
            }
        });

        ButtonInsertarMonitor.setBackground(new java.awt.Color(0, 153, 51));
        ButtonInsertarMonitor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonInsertarMonitor.setText("Insertar");
        ButtonInsertarMonitor.setActionCommand("insertarMonitor");
        ButtonInsertarMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonInsertarMonitorActionPerformed(evt);
            }
        });

        ButtonCancelarInsertarMonitor.setBackground(new java.awt.Color(204, 51, 0));
        ButtonCancelarInsertarMonitor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonCancelarInsertarMonitor.setText("Cancelar");
        ButtonCancelarInsertarMonitor.setActionCommand("cancelarInsertarMonitor");
        ButtonCancelarInsertarMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarInsertarMonitorActionPerformed(evt);
            }
        });

        DateChooserFechaEntrada.setBackground(new java.awt.Color(255, 255, 255));
        DateChooserFechaEntrada.setForeground(new java.awt.Color(0, 0, 0));

        LabelAsteriscoDNI.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelAsteriscoDNI.setForeground(new java.awt.Color(204, 0, 0));
        LabelAsteriscoDNI.setText("*");

        LabelAsteriscoFEnt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelAsteriscoFEnt.setForeground(new java.awt.Color(204, 0, 0));
        LabelAsteriscoFEnt.setText("*");

        LabelAsteriscoNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelAsteriscoNombre.setForeground(new java.awt.Color(204, 0, 0));
        LabelAsteriscoNombre.setText("*");

        LabelAsteriscoTlf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelAsteriscoTlf.setForeground(new java.awt.Color(204, 0, 0));
        LabelAsteriscoTlf.setText("*");

        LabelAsteriscoCorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelAsteriscoCorreo.setForeground(new java.awt.Color(204, 0, 0));
        LabelAsteriscoCorreo.setText("*");

        javax.swing.GroupLayout PanelNuevoSocioLayout = new javax.swing.GroupLayout(PanelNuevoSocio);
        PanelNuevoSocio.setLayout(PanelNuevoSocioLayout);
        PanelNuevoSocioLayout.setHorizontalGroup(
            PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNuevoSocioLayout.createSequentialGroup()
                .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelNuevoSocioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelTelefono))
                    .addGroup(PanelNuevoSocioLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelDNI)
                            .addComponent(LabelNombre)
                            .addComponent(LabelCodigo))))
                .addGap(18, 18, 18)
                .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelNuevoSocioLayout.createSequentialGroup()
                        .addComponent(TextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelAsteriscoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelNuevoSocioLayout.createSequentialGroup()
                        .addComponent(TextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelAsteriscoTlf, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelNuevoSocioLayout.createSequentialGroup()
                        .addComponent(TextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelAsteriscoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelFechaEntrada)
                    .addComponent(LabelNick)
                    .addComponent(LabelCorreo))
                .addGap(18, 18, 18)
                .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelNuevoSocioLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldNick, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelNuevoSocioLayout.createSequentialGroup()
                                .addComponent(DateChooserFechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelAsteriscoFEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(TextFieldCorreo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelAsteriscoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(PanelNuevoSocioLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(ButtonInsertarMonitor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonCancelarInsertarMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelNuevoSocioLayout.setVerticalGroup(
            PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNuevoSocioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelNuevoSocioLayout.createSequentialGroup()
                        .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelNuevoSocioLayout.createSequentialGroup()
                                .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LabelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelNuevoSocioLayout.createSequentialGroup()
                                .addComponent(LabelCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelNuevoSocioLayout.createSequentialGroup()
                                .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelAsteriscoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelAsteriscoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LabelTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelAsteriscoTlf, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelNuevoSocioLayout.createSequentialGroup()
                                .addComponent(LabelFechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LabelNick, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelNuevoSocioLayout.createSequentialGroup()
                        .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelAsteriscoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DateChooserFechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelAsteriscoFEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(TextFieldNick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonInsertarMonitor)
                    .addComponent(ButtonCancelarInsertarMonitor))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelNuevoSocio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelNuevoSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldDNIActionPerformed

    private void TextFieldNickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNickActionPerformed

    private void ButtonInsertarMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInsertarMonitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonInsertarMonitorActionPerformed

    private void ButtonCancelarInsertarMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarInsertarMonitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonCancelarInsertarMonitorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ButtonCancelarInsertarMonitor;
    public javax.swing.JButton ButtonInsertarMonitor;
    public com.toedter.calendar.JDateChooser DateChooserFechaEntrada;
    public javax.swing.JLabel LabelAsteriscoCorreo;
    public javax.swing.JLabel LabelAsteriscoDNI;
    public javax.swing.JLabel LabelAsteriscoFEnt;
    public javax.swing.JLabel LabelAsteriscoNombre;
    public javax.swing.JLabel LabelAsteriscoTlf;
    public javax.swing.JLabel LabelCodigo;
    public javax.swing.JLabel LabelCorreo;
    public javax.swing.JLabel LabelDNI;
    public javax.swing.JLabel LabelFechaEntrada;
    public javax.swing.JLabel LabelNick;
    public javax.swing.JLabel LabelNombre;
    public javax.swing.JLabel LabelTelefono;
    public javax.swing.JPanel PanelNuevoSocio;
    public javax.swing.JTextField TextFieldCodigo;
    public javax.swing.JTextField TextFieldCorreo;
    public javax.swing.JTextField TextFieldDNI;
    public javax.swing.JTextField TextFieldNick;
    public javax.swing.JTextField TextFieldNombre;
    public javax.swing.JTextField TextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
