/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

/**
 *
 * @author migue
 */
public class VistaNuevoSocio extends javax.swing.JDialog {

    /**
     * Creates new form VistaNuevoSocio
     */
    public VistaNuevoSocio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelNuevoSocio = new javax.swing.JPanel();
        LabelNumero = new javax.swing.JLabel();
        TextFieldNumero = new javax.swing.JTextField();
        LabelNombre = new javax.swing.JLabel();
        TextFieldNombre = new javax.swing.JTextField();
        LabelCorreo = new javax.swing.JLabel();
        TextFieldCorreo = new javax.swing.JTextField();
        LabelFechaNacimiento = new javax.swing.JLabel();
        LabelFechaEntrada = new javax.swing.JLabel();
        LabelCategoria = new javax.swing.JLabel();
        ButtonInsertarSocio = new javax.swing.JButton();
        ButtonCancelarInsertarSocio = new javax.swing.JButton();
        DateChooserFechaNacimiento = new com.toedter.calendar.JDateChooser();
        DateChooserFechaEntrada = new com.toedter.calendar.JDateChooser();
        LabelAsteriscoCategoria = new javax.swing.JLabel();
        LabelAsteriscoFEnt = new javax.swing.JLabel();
        LabelAsteriscoFNac = new javax.swing.JLabel();
        LabelAsteriscoNombre = new javax.swing.JLabel();
        ComboBoxCategoriaSocio = new javax.swing.JComboBox<>();
        LabelAsteriscoCorreo = new javax.swing.JLabel();
        LabelDNI = new javax.swing.JLabel();
        TextFieldDNI = new javax.swing.JTextField();
        LabelAsteriscoDNI = new javax.swing.JLabel();
        LabelTelefono = new javax.swing.JLabel();
        TextFieldTelefono = new javax.swing.JTextField();
        LabelAsteriscoTlf = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PanelNuevoSocio.setBackground(new java.awt.Color(0, 0, 51));

        LabelNumero.setText("Número");

        TextFieldNumero.setEditable(false);
        TextFieldNumero.setBackground(new java.awt.Color(195, 195, 195));
        TextFieldNumero.setForeground(new java.awt.Color(0, 0, 0));
        TextFieldNumero.setActionCommand("<Not Set>");
        TextFieldNumero.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        LabelNombre.setText("Nombre");

        TextFieldNombre.setBackground(new java.awt.Color(255, 255, 255));
        TextFieldNombre.setForeground(new java.awt.Color(0, 0, 0));
        TextFieldNombre.setActionCommand("<Not Set>");
        TextFieldNombre.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        LabelCorreo.setText("Correo");

        TextFieldCorreo.setBackground(new java.awt.Color(255, 255, 255));
        TextFieldCorreo.setForeground(new java.awt.Color(0, 0, 0));
        TextFieldCorreo.setActionCommand("<Not Set>");
        TextFieldCorreo.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        LabelFechaNacimiento.setText("Fecha de nacimiento");

        LabelFechaEntrada.setText("Fecha de entrada");

        LabelCategoria.setText("Categoría");

        ButtonInsertarSocio.setBackground(new java.awt.Color(0, 153, 51));
        ButtonInsertarSocio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonInsertarSocio.setText("Insertar");
        ButtonInsertarSocio.setActionCommand("insertarSocio");
        ButtonInsertarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonInsertarSocioActionPerformed(evt);
            }
        });

        ButtonCancelarInsertarSocio.setBackground(new java.awt.Color(204, 51, 0));
        ButtonCancelarInsertarSocio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonCancelarInsertarSocio.setText("Cancelar");
        ButtonCancelarInsertarSocio.setActionCommand("cancelarInsertarSocio");
        ButtonCancelarInsertarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarInsertarSocioActionPerformed(evt);
            }
        });

        DateChooserFechaNacimiento.setBackground(new java.awt.Color(255, 255, 255));
        DateChooserFechaNacimiento.setForeground(new java.awt.Color(0, 0, 0));

        DateChooserFechaEntrada.setBackground(new java.awt.Color(255, 255, 255));
        DateChooserFechaEntrada.setForeground(new java.awt.Color(0, 0, 0));

        LabelAsteriscoCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelAsteriscoCategoria.setForeground(new java.awt.Color(204, 0, 0));
        LabelAsteriscoCategoria.setText("*");

        LabelAsteriscoFEnt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelAsteriscoFEnt.setForeground(new java.awt.Color(204, 0, 0));
        LabelAsteriscoFEnt.setText("*");

        LabelAsteriscoFNac.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelAsteriscoFNac.setForeground(new java.awt.Color(204, 0, 0));
        LabelAsteriscoFNac.setText("*");

        LabelAsteriscoNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelAsteriscoNombre.setForeground(new java.awt.Color(204, 0, 0));
        LabelAsteriscoNombre.setText("*");

        ComboBoxCategoriaSocio.setBackground(new java.awt.Color(204, 204, 204));
        ComboBoxCategoriaSocio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ComboBoxCategoriaSocio.setForeground(new java.awt.Color(0, 0, 0));
        ComboBoxCategoriaSocio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E" }));
        ComboBoxCategoriaSocio.setActionCommand("comboBoxCategoriaSocio");
        ComboBoxCategoriaSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxCategoriaSocioActionPerformed(evt);
            }
        });

        LabelAsteriscoCorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelAsteriscoCorreo.setForeground(new java.awt.Color(204, 0, 0));
        LabelAsteriscoCorreo.setText("*");

        LabelDNI.setText("DNI");

        TextFieldDNI.setBackground(new java.awt.Color(255, 255, 255));
        TextFieldDNI.setForeground(new java.awt.Color(0, 0, 0));
        TextFieldDNI.setActionCommand("<Not Set>");
        TextFieldDNI.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        TextFieldDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldDNIActionPerformed(evt);
            }
        });

        LabelAsteriscoDNI.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelAsteriscoDNI.setForeground(new java.awt.Color(204, 0, 0));
        LabelAsteriscoDNI.setText("*");

        LabelTelefono.setText("Teléfono");

        TextFieldTelefono.setBackground(new java.awt.Color(255, 255, 255));
        TextFieldTelefono.setForeground(new java.awt.Color(0, 0, 0));
        TextFieldTelefono.setActionCommand("<Not Set>");
        TextFieldTelefono.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        LabelAsteriscoTlf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelAsteriscoTlf.setForeground(new java.awt.Color(204, 0, 0));
        LabelAsteriscoTlf.setText("*");

        javax.swing.GroupLayout PanelNuevoSocioLayout = new javax.swing.GroupLayout(PanelNuevoSocio);
        PanelNuevoSocio.setLayout(PanelNuevoSocioLayout);
        PanelNuevoSocioLayout.setHorizontalGroup(
            PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNuevoSocioLayout.createSequentialGroup()
                .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelNuevoSocioLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelNombre)
                            .addComponent(LabelNumero))
                        .addGap(18, 18, 18)
                        .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelNuevoSocioLayout.createSequentialGroup()
                                .addComponent(TextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelAsteriscoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelNuevoSocioLayout.createSequentialGroup()
                                .addComponent(TextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelAsteriscoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelNuevoSocioLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelNuevoSocioLayout.createSequentialGroup()
                                .addComponent(LabelTelefono)
                                .addGap(18, 18, 18)
                                .addComponent(TextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelAsteriscoTlf, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LabelDNI))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelNuevoSocioLayout.createSequentialGroup()
                        .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelFechaEntrada)
                            .addComponent(LabelCategoria))
                        .addGap(38, 38, 38)
                        .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelNuevoSocioLayout.createSequentialGroup()
                                .addComponent(DateChooserFechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelAsteriscoFEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelNuevoSocioLayout.createSequentialGroup()
                                .addComponent(ComboBoxCategoriaSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelAsteriscoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelNuevoSocioLayout.createSequentialGroup()
                        .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelFechaNacimiento)
                            .addComponent(LabelCorreo))
                        .addGap(18, 18, 18)
                        .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldCorreo)
                            .addGroup(PanelNuevoSocioLayout.createSequentialGroup()
                                .addComponent(DateChooserFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelAsteriscoFNac, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(5, 5, 5)
                .addComponent(LabelAsteriscoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(PanelNuevoSocioLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(ButtonInsertarSocio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonCancelarInsertarSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelNuevoSocioLayout.setVerticalGroup(
            PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNuevoSocioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelNuevoSocioLayout.createSequentialGroup()
                        .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelAsteriscoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LabelFechaNacimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DateChooserFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LabelAsteriscoFNac, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LabelFechaEntrada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DateChooserFechaEntrada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LabelAsteriscoFEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelNuevoSocioLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LabelAsteriscoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboBoxCategoriaSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelNuevoSocioLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LabelCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28))
                    .addGroup(PanelNuevoSocioLayout.createSequentialGroup()
                        .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelAsteriscoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelAsteriscoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelAsteriscoTlf, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)))
                .addGroup(PanelNuevoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonInsertarSocio)
                    .addComponent(ButtonCancelarInsertarSocio))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelNuevoSocio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelNuevoSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonInsertarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInsertarSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonInsertarSocioActionPerformed

    private void ButtonCancelarInsertarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarInsertarSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonCancelarInsertarSocioActionPerformed

    private void ComboBoxCategoriaSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxCategoriaSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxCategoriaSocioActionPerformed

    private void TextFieldDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldDNIActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ButtonCancelarInsertarSocio;
    public javax.swing.JButton ButtonInsertarSocio;
    public javax.swing.JComboBox<String> ComboBoxCategoriaSocio;
    public com.toedter.calendar.JDateChooser DateChooserFechaEntrada;
    public com.toedter.calendar.JDateChooser DateChooserFechaNacimiento;
    public javax.swing.JLabel LabelAsteriscoCategoria;
    public javax.swing.JLabel LabelAsteriscoCorreo;
    public javax.swing.JLabel LabelAsteriscoDNI;
    public javax.swing.JLabel LabelAsteriscoFEnt;
    public javax.swing.JLabel LabelAsteriscoFNac;
    public javax.swing.JLabel LabelAsteriscoNombre;
    public javax.swing.JLabel LabelAsteriscoTlf;
    public javax.swing.JLabel LabelCategoria;
    public javax.swing.JLabel LabelCorreo;
    public javax.swing.JLabel LabelDNI;
    public javax.swing.JLabel LabelFechaEntrada;
    public javax.swing.JLabel LabelFechaNacimiento;
    public javax.swing.JLabel LabelNombre;
    public javax.swing.JLabel LabelNumero;
    public javax.swing.JLabel LabelTelefono;
    public javax.swing.JPanel PanelNuevoSocio;
    public javax.swing.JTextField TextFieldCorreo;
    public javax.swing.JTextField TextFieldDNI;
    public javax.swing.JTextField TextFieldNombre;
    public javax.swing.JTextField TextFieldNumero;
    public javax.swing.JTextField TextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
