/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

/**
 *
 * @author migue
 */
public class VistaActualizacionCategorias extends javax.swing.JDialog {

    /**
     * Creates new form VistaNuevoSocio
     */
    public VistaActualizacionCategorias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGestionInscripciones = new javax.swing.JPanel();
        ButtonSubirCategoria = new javax.swing.JButton();
        ButtonBajarCategoria = new javax.swing.JButton();
        LabelActualizacionCategorias = new javax.swing.JLabel();
        jScrollPaneSocios = new javax.swing.JScrollPane();
        TableActualizacionCategorias = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PanelGestionInscripciones.setBackground(new java.awt.Color(0, 0, 51));

        ButtonSubirCategoria.setBackground(new java.awt.Color(0, 153, 51));
        ButtonSubirCategoria.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonSubirCategoria.setForeground(new java.awt.Color(255, 255, 255));
        ButtonSubirCategoria.setText("Subir");
        ButtonSubirCategoria.setActionCommand("subirCategoria");
        ButtonSubirCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSubirCategoriaActionPerformed(evt);
            }
        });

        ButtonBajarCategoria.setBackground(new java.awt.Color(204, 51, 0));
        ButtonBajarCategoria.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonBajarCategoria.setText("Bajar");
        ButtonBajarCategoria.setActionCommand("bajarCategoria");
        ButtonBajarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBajarCategoriaActionPerformed(evt);
            }
        });

        LabelActualizacionCategorias.setBackground(new java.awt.Color(255, 255, 255));
        LabelActualizacionCategorias.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelActualizacionCategorias.setText("ACTUALIZACIÓN DE CATEGORÍAS");
        LabelActualizacionCategorias.setToolTipText("");

        TableActualizacionCategorias.setBackground(new java.awt.Color(204, 204, 204));
        TableActualizacionCategorias.setForeground(new java.awt.Color(0, 0, 0));
        TableActualizacionCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneSocios.setViewportView(TableActualizacionCategorias);

        javax.swing.GroupLayout PanelGestionInscripcionesLayout = new javax.swing.GroupLayout(PanelGestionInscripciones);
        PanelGestionInscripciones.setLayout(PanelGestionInscripcionesLayout);
        PanelGestionInscripcionesLayout.setHorizontalGroup(
            PanelGestionInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGestionInscripcionesLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPaneSocios, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(PanelGestionInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonSubirCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonBajarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
            .addGroup(PanelGestionInscripcionesLayout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(LabelActualizacionCategorias)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelGestionInscripcionesLayout.setVerticalGroup(
            PanelGestionInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGestionInscripcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelActualizacionCategorias)
                .addGap(31, 31, 31)
                .addComponent(jScrollPaneSocios, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGestionInscripcionesLayout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addComponent(ButtonSubirCategoria)
                .addGap(18, 18, 18)
                .addComponent(ButtonBajarCategoria)
                .addGap(127, 127, 127))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGestionInscripciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGestionInscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSubirCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSubirCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonSubirCategoriaActionPerformed

    private void ButtonBajarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBajarCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonBajarCategoriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ButtonBajarCategoria;
    public javax.swing.JButton ButtonSubirCategoria;
    public javax.swing.JLabel LabelActualizacionCategorias;
    public javax.swing.JPanel PanelGestionInscripciones;
    public javax.swing.JTable TableActualizacionCategorias;
    public javax.swing.JScrollPane jScrollPaneSocios;
    // End of variables declaration//GEN-END:variables
}
