all: servidor_ncurses revision ateoria atodo

servidor_ncurses: servidor_ncurses.c comun.h
	cc servidor_ncurses.c -o servidor_ncurses -lncursesw

revision: revision.c comun.h
	cc revision.c -o revision

ateoria: ateoria.c comun.h
	cc ateoria.c -o ateoria

atodo: atodo.c comun.h
	cc atodo.c -o atodo